// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from adaptivecards.djinni

#pragma once

#include <functional>

namespace AdaptiveCards {

enum class DjinniTextColor : int {
    DEFAULT,
};

}  // namespace AdaptiveCards

namespace std {

template <>
struct hash<::AdaptiveCards::DjinniTextColor> {
    size_t operator()(::AdaptiveCards::DjinniTextColor type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
