// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from adaptivecards.djinni

#pragma once

#include <memory>
#include <vector>

namespace AdaptiveCards {

class DjinniBaseCardElement;

class DjinniAdaptiveCard {
public:
    virtual ~DjinniAdaptiveCard() {}

    virtual std::vector<std::shared_ptr<DjinniBaseCardElement>> getItems() = 0;
};

}  // namespace AdaptiveCards
