// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from adaptivecards.djinni

#pragma once

#include <functional>

namespace djinni {

enum class DjinniTextColor : int {
    DEFAULT,
};

}  // namespace djinni

namespace std {

template <>
struct hash<::djinni::DjinniTextColor> {
    size_t operator()(::djinni::DjinniTextColor type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
