// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from adaptivecards.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, ACDjinniTextColor)
{
    ACDjinniTextColorDefault,
};
