// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from adaptivecards.djinni

#import <Foundation/Foundation.h>


@interface ACDjinniBaseCardElement : NSObject

- (void)SetSpeak:(nonnull NSString *)speak;

- (nonnull NSString *)GetSpeak;

@end
