// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from adaptivecards.djinni

#include "DjinniTextBlock.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ACDjinniTextBlock;

namespace djinni_generated {

class DjinniTextBlock
{
public:
    using CppType = std::shared_ptr<::AdaptiveCards::DjinniTextBlock>;
    using CppOptType = std::shared_ptr<::AdaptiveCards::DjinniTextBlock>;
    using ObjcType = ACDjinniTextBlock*;

    using Boxed = DjinniTextBlock;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

