// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from adaptivecards.djinni

#import <Foundation/Foundation.h>
@class ACDjinniBaseCardElement;


@interface ACDjinniAdaptiveCard : NSObject

- (nonnull NSArray<ACDjinniBaseCardElement *> *)getItems;

@end
